# sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_script:
  - npm install -g lab
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < lcov.info
before_install:
  # iromain/api-bootstrap refers to https://hub.docker.com/r/iromain/api-bootstrap
  - docker build -t iromain/prestasedis .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push iromain/prestasedis

deploy:
  - provider: heroku
    api_key:
      secure: lizdea+zl1acWAuOxMbdvJrkkyjiC4xXxgVYzW6Kayxe8Be902D0W8JgP5Kt1vK3838mjW3d222zP0rA3O2cbe/5odkAUsx+b9QmCY83SOnAbINe1Kkum+Hjml0gjX4m1QC+KLiQeln7kMUGpPeLerdT47qbmGuRHjq3tzYS/SyHbKOsqFHvSZofgXekaM0uQBOPojJ7zxSt6nydohWpTLOCRI0cz7sITY1zCX8MN+VyZB8zzvoJUQJn63U3EboX4zesgnKfhtl1hFSOA4vTn8dcg+LJMm52f1wmaJSb8xggtk2mhfLgMPhxKoDjoHRNbkQmJ+RbMFKfTS0uTport2svxzVyikAHJYZKnnUSnlZupzOnlT53LZ//4VT5Uwj4b+j4oFHuF3ttYKswwz9GYGy1PIdMM6te40ZeNJW72sOUGTcvNNZfh2stSQekJxMvqBv2RgF7Oz6olqP6gPjy7jlHEyFh/nwA/C8MTfZ82vGucwpAkfozjpHdEgDgdb8f+jL0oGkCWd6EoygtNCksdlFA/dK1UyFCdUrNpacmUpNijo9N0iYa8KoDDHdfbfMeUGVD206mnuH5M3Pmd3iI9Eh7yYTqEW1jAoFMWqi0uXEN0HrHUtrzy2NWZE895mNJ1xnH/4B6vYy079tc8JvylCm+hjDRX8FmWDPtKn8nGKQ=
    app: prestasedis
    on:
      # iRomain/api-bootstrap refers to https://github.com/iRomain/api-bootstrap
      repo: iRomain/prestasedis
#  - provider: cloudfoundry
#    edge: true
#    organization: romain
#    space: dev
#    api:
#      secure: UwQTXYXjU0n4o9PDWezZ4H70nLuq2UY0GE4f2PLmvE5hMzoz5jQnVdoGxpqKqtTZKBuRsjKinIhOIcyofM4YvGBTg+MfLfvYMESEVWOj15SCogWY04JWicjV/kmEURxR3xnbPGNdGPChjvK5rA6wqDg+wZgSIxp6IGYIYWpP4lnNqZpE1U7z5G99gt5OMHu3Zz7eo7KZTzLT1cQneXRZNihOAMdM4KMjfR9QTp3vVCGSwR5CQZSu+P9GbwBZ6XzrmjUU23Dgs2aEcOOekj5F3HqAF9Isl4oxOEOSg7Gm/up6EvTmfwFf9ncSvcAc5wmPLVsN12A5O4Kd+YK/O3Cg/R1+CivqG0ZPjYP5A26sghkDhntpuB+aXv005IbxycuwbjdNjcby42EMCnVpDkXy9RQ8RoNubRp1HI/nd4EZJkKQ2Pod06yW547J6CAbACTv1lu1Qr1MhMEvIWYK/mQqwaX9x5i4UIPO7Y3/LXltjJ+7Q9gUz+DFOFvXyA7Ha8k95ySh9NoOj8ZS30BiebCL6G1USAyFx3aINBJx85fTZprXs53o5V8860Ru+sUL9POWRDwJeyC0YEU0y3wEbutfutmfTMiXOL5FISl1hxaCbl9OO5Bu+MjoqCRDV/G2FKZvzbYWurISLYIfrWwG5fIxPSRUtWs+3VNqFMTKyRN+pBI=
#    username:
#      secure: PfQasOZvMaCWaWf3xf67rmBJLsKfTKEDvEixuxN3GDV1S9Vr2V/oexyemOl3SJOmhuMOAt9yREQootcR3pfubEJyUOrbpH4s8pVOHiJbtR8U+HyFsdslQB3lozeeHYbvds8nIZxNRxvMl30eECUqOPuTRwOhlQo//XHP4hcSvZAEEpUBZKjcj/OZNvx5xCjMFWE8t275mFjp9MAbi0LbSfiwdtEeBeFpXo9zZCeXFKRpEgb8QKVLcp4WxVjMs2aSY9OHgw7ktuG9fCFvt0Ekp2o0WylF9AS6V+hh7INnop9O3aoJgtaKa2pzOIDOD/6C1AtHhX5Iu9XI0J00Ci+lSxj5ppkNl8uCovYiW17SNR4nJnaZkKHwR5i6rcnmWE3pX7k716uSgEF4eR9Xz/1Wo8Y5+Y5CqENph+/9V9iss+qMbr4jU/9hL6S62YyMpzGSWmC2PJFGsvLIcIEMvdG3kbsRmVmNVG/+3e7/hFNKkxyKEKQ0cwdqxfZeTJYsULObJU+qduruyaWKHTEeBHKW9WcrRszQu7xmZqeIjoIKg4G3X4frTld/Ea2YDmhl73Um1nRLhiVt7fLy0m2MiAstMaLmspaGQ8nAAFOHmmj5bFN44imZzphX2aoc8i92EXipNMK8pg5bGY5pBASZyoa/f0z/IK+MkaBK2VaElNVOyQI=
#    password:
#      secure: OsJkfhKwFsWmmD+a/DPajkv9Nqu9hjzbxcxh9OP+9mH6aiVa4PMtxvkGjp2zT2YbmNPDpFq6kMaY9+QbQDW3xD20K8TODVB3fWoXvAe7nZk38B7lhZl9CwJJO1Eaweg13k30HYmypO/xubvUQ1PrX+ZXFFiXbibFELEzH3QSK7b72vfFvuh7owLrXH3uvkwSSbx5dRZpmCSrxjdS2kJJ8uSkSAxNTEDyxaqsLUEe1CD20wgTfg8x8cSQuJ+ZqGHdSjhH+QZQK8WIfu9L1GVQHSYb9tfi7YvAupFbnNbIzuacnHmlLnWWXMx3V7KXLhU5eqFtiSiuojNowB18qj+zmc+bldT1ITgwuDDa4N4LtMgN7/9YfqR3iGh7O9riyU5QaLT8ycVRe96pZQJyUa99lpyi5VJgZoF4EYuHmAI8SX2Q5APAr9uBRTqkXic+C+/G6nVc1x2Ovv7DObVZiuPqtGPken2QoxbdorqhAyhEE6leVBxgNux0rc/Udb2Id1tRTo6lVUFDtQwqIiHRs7Q3IkwrpZmTciwOH643T8TZutns5yz1UY0E3Ah0raLBBqf7i3y2S2WnjI9DfXTDOsgK88VE1Krlo5HYepIxsllY8pKEdJa5/myZt9QD5DVNByHp54VhjAYNw3/6XIz8DXpBpaZvotoj15INjKXB1mUWkv0=
cache:
  directories:
  - node_modules
env:
  global:
    - NODE_ENV=test
    - DOCKER_USERNAME=iromain
    # travis encrypt DOCKER_EMAIL=your@ema.il
    - secure: RZG6wthD8u3oD2ZEKBQYEL4TajW8dg1y9acTsXjC8V6+biut9yHO0SgyWlV8Xi6SR+ixEHdg+yi6XS4PJEiSMGGDuQslk/8kAoihgiAvXHE3lWcLs49TPocGBtkWRnq1vNrtnEikhG6jJADqlYBZ9TI7VRI14Eu6oNTMXO0hrJbAiemDaKO0cDnoSjeHUSOINZ7t7Rl+0gJVT2YuW3C40B4loAyJFiWIi7Y6YXcm8Kg1BRWLnFlixiAIBheUjKH23p9kNbp8zPx/6Vz53QPV4ILEzzAETo5aYwEsEotl4v+TziYOVkCM0+WyL7vupIzf7SkCDOQxBmpFRd87nywYdI3PXIPkEDwWVwo682vCNC88GiONUd6IPobwQxPOYunuKeId18O2G6X9FGzbgtaAkNysJV6uQb3R5Shf8M/qr2mOLeH6VcBjbze2R1JLWpBuFWihAaama02P/IoWuFP7UpD/nWByo6gCzGIK/2w7ZN67Xjm8tKMusrR+4qjrjsr1DYBP5xOaDp1PhNdeKgmuSNMhG8+nz9oSlwHUglf5c6DN8S2wzSDbM1RUaJdLtXSz5pRqVupKmptx3sl3LdZ+yZMlzY1FnsTZh43k7RWsVH6559bznJ2VzrvI5UTbnyUP2ujR+gmUOxSi9Jh9G2N0Hd7GDQytSLf8M9aBoEgTNUc=
    # travis encrypt DOCKER_PASSWORD=password
    - secure: GkeV0emx9PVAqIiF7GHImyplGyXg4p7k3UVI10llac9joo3rt9xIsoQn+DMmWutVVnTbWbsSyf1zHbMbyFNvRqlwEtFI9lEGltNACWXOMYZS60dmUKm6GM7Q56wKVV/EJb7ezaQinRZaIvmXTOTZYeSkrvEEd6XfANyq6qq9c177TCYaIi2RRQebjvE/6gE8ECWsG6wtRSQmDWuEOlH5dkDc3XInWu69MAyM4XWBZiiqQz18SmtUgyBGTy8vLZqvlV14qV6LHH3eEz9elGIlQBbAhebQuZS75/6PKMS6hD+zYIbGrXowswpS4reepTT6PzI5uIAyD0oTgYSuOHJelMjObDVHF3itkkIbVpKTiKSj/7OcpvRjhzY2jWuYTE7Dfd7nC1z7ugyhbbNk9yfV8REmArG+evwZQ6sy9NzoMdXW5vHvfEvJYUB7517f0AApPJIlunCwKdOhHAyxSUqR/IyZ4iC/yCRKLkPuV/HKQcNqpHuLD5qnk7bb3spl1iJVpx2Curd5MsC4HVl9eUFDQ4eEoY6BPXo78XZBBAYqfmuj8u/tY6L9b2fjQ1kTsh/FRDPgW95ONM8ptcQww2nBlLSMrgguxsn+YDNDy3rfeaJ1SbhWem7kNfyshEzbpsuD/2V23Pe76ueGEqrMFbM/wTUYj2r3QVDyso1CLZVqYyA=
addons:
  code_climate:
    repo_token:
      # travis encrypt TEST REPORTER ID
      secure: ThVQ4SZMfWzRICW2d1zqPfP6E/1+PCLPU0kE0+yfBe/GA+fCdS1h47TcTQnGE6/9H4Pmh1pwhogYegz2DyFFFA/qGoqRwM+qOYJ6vGnU4IwtkCMZeQfLLPNqjGkfYH+psy7BthJGrWrojJncJ4ybY3F2EGy1oRG+i5NIgOEkOVUB3ZoiOmNPnJ5uXXZDyHW62fAzlAu91CUf0qj+pMiRSn588EfKVhrZChJ9Q+SyEtIZ21PCOqmCvvjGcXiwKnkqx40hyNwSpcrWxlPtJOj5rx/MAUOEqsXwNL2WQeDZIZ1fJMPvLm4Uewen3fkUz8Q51LIfKBU4kUgG54aAt/HlIHP0STbWbFbVlhc0JIM9fZuMLSSt/DPr7T3uKcobmbUZaLcWSeOUGywXcKEOlO7FpAorR8gyZv8AhqAGTHc/22CnBLO8C/Cnq+vUCCCCmTNn8Cv9lrs5CFT5mmCDI96+0vSR/tciwhijz4ObkOGkQbMnNt+twZiqN+KgR0EPckDoIHNpYYXmwM8zKn/pDXAQai848VRCbPV5ccFVj1mfO1Z+/sOwPc2hhMzAExCgpGVfnMl7oeIbGYJceL6+q0KxxS8K8rkJQzdbF+iCXgYrg6pa6CMsQnX7mcOZIqHqwCyjDmUJG09bejADoidyK4cuGC+XbKNNK9jzcXznXld0gJU=
