language: node_js
node_js:
- node
services:
- docker
before_script:
- npm install -g lab
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < lcov.info
before_install:
- docker build -t iromain/api-bootstrap .
- echo $DOCKER_PASSWORD | docker login --username="$DOCKER_USERNAME" --password-stdin
- docker push iromain/api-bootstrap
deploy:
  provider: heroku
  api_key:
    secure: gq0EZf+awlwlZbnOg6tR+Xax758QY6BU6kWXkTsd+xcsBZkOnA0ZyVFezza6u72YYvcs18fUZNlPhv3YgK0J4V+3Q2YU56JkFPDVu4udsf+NiEubNeKJgYIZGLR0Ts3PyALZwEorVYkD7kv2Y+amr8k1tRMf+xNb8PeuhRQTYkqLolZRXivQ6IfLAXHbR3FM7HNE+oxHnuWgTnHY9dYYY39BD4wfICARKEL+TuuZ7KWlYEhasSZfbm67YR+lnjflr96d785kBFmOQcWR50fCwaaXP/DcMfJq2rJWPAtZQX9t/4nseRhy7HwUiMowopUCttCK6T3RFbyA7YySScQXJOTxcqA9F8MNnRFmW4rWTARMKkJpBuQLSYnh9u+q9p+aMRDWo5Daw4Rc7bIlyraOg7ijifv+L6ztBsh7sXbxpOa02G69fq2YuAJMYqvrJaumFB8h2kyYuoAAfBkBpAXxLdztma1c3i4lzJTMjMQ941+I5SlpMLQs2wHhD3ydt6DBqkogLgUnkudsITcUPZE5fAAA9gfHr1qFPSsLebXpYb66787Sn9wgfz45xd+TmSB0SRm93FEE40Bd2ECXy/DzKwaIDVzwdg34hkGLfnAiUuOQcB/0hdnDdT7cZPVDmvHm8L4F+1tKmPWKTrQGYP+63HoesNG0De5Qmaj4gMWlRlA=
  app: api-bootstrap
  on:
    branch: master
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=test
  - DOCKER_USERNAME=iromain
  - secure: doTA/m0k7fwh5STxjhS6xvR+Pi5EkRK3/agO8NTPvo3H3VjHz4R7vN4rB0Gxe/CPi58yz1vmAuY+oiN3N3pJOH1v5h64gG8Bqn1KaAd3y/cE/xlkt5Nttr4QkQvwU+MDEQZDjcDWjP2xuuCLfg4pHPJvabVEN0yyYdWx5EzYKFiygVFLPPBKgtqljlxc/z16If2igaP7xP+JDwjaeN/V/29F+vo3hkPPSvFhr5GVy0AeQfJIO9E6puc0Q6Z8mVMwk4ThHS7UiW6A1s1vEsUajQTzY0sOgsUHNO9fVCtUHb0/+81hKCHD4NOQwmFOGTXqhn2kezqOazohjKYlQCnB5xI0Z2hQuBAcmdiuzMCVWY9R1bNQDNzEDKc+e7q65O2ab3npzJ7t11Pdn15WZBPTYflgnLAH5N36mahNiUYJgSBGZeWZ58K9h8Pgm5X7zRpQIvBQrDcCFRBpcmxD90AnciswjlqW3kArRq6CPn7R3Ye3ioTQqGPf6jUilsydpocWoECsNd6wn1VAr0wTS8q5oYwuP+AmWIejuzt5p8M+FiISZbQwcZzZGVOWSCOZwqzuPoSEedMoVNHj55geLB3WUvu8CKYSZCC3Obi1HZRnCPEX4H8kjV1aaMlgYstnmtIXVSbBlsyjP6rak3hzReO6rioZquVYKe9AjW4RBeH8tU0=
  - secure: VSppJD+TkHozdjBMceut5HzMRyLU7su+9r3K6zpGOC0g1KCufMdJKGYdxqslRv1QRAxod4fCGyFv4F1Qvu+e4nEUMRxuGQjo9GXhkU6Z1anKRbkVZ0Vpq+INIoFowB1j5qUKqsE5iARDPNHvN5vv+d6Jg/+2fP+SRUy06TiPT9Kz/TLNNB3pzAxplqO6xX4FB3xwyRsr1gz8Q1Q4dYbeDVI0QUMlq5IATlCqD/OxOijaMIS4xQGtj26Lf9ZKqeS81iZwf6t68GeJXNXU0ZZTwD0h0Zmtom4vsQedTXVZS/5WaPdimOSh09AJcftZ+YKX2jlMtCa573espNNrpkn1wTBYMcXK7X4aYnheK7B1bmE6ylaT6Degc+L3e9ltcLp6mxJTHKb3c5GD8ECDWqMyhIs7rDfjKeCprQsIbZ9aSi8ryLeiXEyGsqq25KRzN6+YLpGBic6Oc71y985/ZmTqZHidJXSvdC9MsDPhA9a3uBhHBlQCqei7iwArRAYdDRfgOyg1CcZy+8GmtMC7h+12o1x5ygkFPDGR1yM0q/buvZBJokmaKDL66pFvG4iA31X2ozP07x+fO4U3q4DnXqfQiJP/a0qGCLebmk6vYiUVg7TmYD5n/uaBTQURPDKbNUSg7+I3emHWZqgUwESeotRYbXr5N+Gpnom6gyRMT/VRWcs=
addons:
  code_climate:
    repo_token:
      secure: G/8d392Ccqby6+lf5gJx+z0EKTvSriMr3HnVkxJWwq4tH3w0/iQCslA7mF7ij1xyFUY7V4tT8CDQoP90wiwRNZwM4/jBpwojAR4wM1RVtdcjcoI638F6F7nGdaqYSHg8DVLUHYJKGToSUEd7qNw5NiEkt9Di4n+LA0egyactqfcxfbNM0npXih22OK1swsQ3r8cYznHRDKXyYAcPKI81xaqtaxC+a+pYynIokLYwPyJiEB9e2AmOoZBN4BA6lzag9xKJ7r7wA9G3KRJ69RGXO4J3sAwFPNiOcUSCURyWRbo/STvV84cSD4H283fTvy3yyFxxQQuxQMyJx9ClzpHiA10KB2iM0gwWhzAd4J4hYThtbHL/+1Gdp0UaSypY2sRa0F7haUsD/XptAVK20Jp7B9olZD7vp4H2wRneVYDwhZrvmp1R3K2mlNe7ogNi0Y01rIX3bCCX7v1C+d0XhD5mGJUDxBTkpneG9Q7U34N9hydCIqIL2BxAw0QCidp+2SICOVqWpCVtxqXtSt9otnb3/cCgTP6loqFUtCepFUBPpyiVSTWUr3Kll2M+doc+qpNIyOpajmDdu00fvH2w+t9WfF1e5/5jxrsaCvr6WxDB/G4UIY4PUsjyPaiVZ2yGaOS4H4kourIRaFQbrcuf6HFqhGb9oJytYinrG68g1SvkXTQ=
