sudo: required
language: node_js
node_js:
- 4.1.2
deploy:
- provider: heroku
  app: bootstrap-api
  api_key:
    secure: RtmGsCu+ZxhuMRAJ12gkVGaTTWuMFYUI+Vu8iizD6I7Z3V0/lojzivYjw+gpPo2Se8FkhQHNJXzv6ODe5+1E5ezyvXc+bNKjnm6lPmzGDuFMx6jTHlFTcWAAObTbpFylS1v+ld34dq8DAccyy4/j1Os9dikCMtftkG8RW0lZX6OP2KX12Xj+MbaiVr3E8BsfCOidTf5xj4zk92xmq4v+dWHGw+tC/bifHL0Ax1MDWNtSN4+QiQ6JSBseaJ5xUbIzgyD0IYQ+ROQo7PruS5Qfwr2B1yQ1jJIG8+aDGaeNWBxyGT54IjFRoG4jOQmPRvape9uh/07E8ZQtGhlPsDYtv4y7hbepzUYXlYFOWmTPqy86ukp+kstWuVLa70ZcE9vUf7KzxjMx9NPproYWbRdapDlRPUd2/FZxW27yd2iEOTiALIyRWZfqN6EdvHIVih27KnX5kPZr3uo7zzEN6kFaPYmiluQVLKHdyfSehnADnDyztslSyU+WQkTwGaWHFFRnl49Z1SeP8k9+hfv3hUk/PSMNU1F9+/Dvy367fiBiaFJ8K/KFJhBJeTGSIDJj8504kgA4ORo7TEt191r9j0d5H4HWQ5f4/Pkw6ahMu1fxpmjryt34G0JL2gSRhHUtzNta3sTJS+LPGbEgLX5E3WcjDiIXWG+Io3VQTvrf9/V+/eI=
