sudo: false
language: node_js
node_js:
- 4.2.1
before_script:
- npm install -g lab
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < lcov.info
deploy:
- provider: heroku
  api_key:
    secure: nKrNGlvXdCAVBaIFkkajRaAx9XnQrtAwvnOX6DwNdLe2ic0ZJl8/QPt54nt7WX1+8ik/yRtmRswzc5XxIDCob3s7f2tjTfjE9xXYocB9LkahwV5VH2omnW1FwdCOJbkWiuzb3F+ffJfExNrltjWeWKHplQ3RSvSLpNQe48iYa5bppQZtFaAJQRT2k4fLu2oS5T7Bx0FI+e5FTFVLRMXqMk3OBTV4xK4A0Q9VPqNLc31yIJH1o+LEYisbbFqIdL1E4v/JhvjYVKPknqru3Hkg6cwpVnOyDMHCaGd8MZw7bKTD8xI/u+8C8KTCXq2LAx3oTi+jpPq68fjRRrHQl6vrdAYEjB90iEWJjqDx33yjMFawggQOewwZ88IaYli1AQHtwIlG6i1NJ4wWJz4OxXtycVC3U8bxhRNHCMfDbDqrxEDO1VBm3JRaOEEPQ1gJMB0ODr3EIgCHdCvwA6FHBHrSy+WP2+eXGJ0cuVY/51aUpIjdyrLuK31yZezW48HjUctmT31nmmUexPzPu5sqX1qJf/17+GRQ7BuoFAlz7v6OfrsnwFLnSdS9fz9ejD39NOzq4OoB+DyiudRd2wzn6a3DQbwu8G6q2+u5O3ZP6ubL1CwilkX43HjLWjCB7joEb3Mjv2GX4LBStM+iPvRSlEwbO1H3AEP+aZPHcs7AVGVe0QE=
  app: bootstrap-api
  on:
    repo: iRomain/bootstrap-api
cache:
  directories:
  - node_modules
env:
- NODE_ENV=test
addons:
  code_climate:
    repo_token:
      secure: YOOXu3O3rbyAet6EXdpT1aXrEfkVGJ6MsbF8bDkdeD8pQTq84Y/q4v5Tpsv74xeqCwdnkYmn9bC9YLo3ancmHwE6/w78sZWvos6AFWaqhd6lkyCjV5lMQiDvOdEL6Y7GxNX+G8p/L67wcp1hZIwmsljRKjAXsRxusdTInNHYPCT+ha/ncE3CU9T5IUCcaZ7DU2O0Sl20elxxB4si1jVMtPs67/wIW1LW3zRIOL/mCwEnMa45nAhhpvo6J+5DpYgg4HARUciUSQWkgrMSzJHRKISG6mdbBaWlOKcSI0DOE7aBhPMY+b/qlNY/L91sfMmbJ11rbKjHAb6g3G/gPYhjPvqlTO1vtNCRvSNCtbFaoRSth3Vj/7pQFN6ZJls03dadoOgSMq8BApl136jJgsOpwkIDM4+i+Gs7pI+BixTPAmr+l27m3i0tx2lDgFiL5ibhIVOCMADE2BUo2MezLI2TgLHON2ZEaaq1b7kF61glA91xQlefLD42RAoPGrJxFrtvicQXJYh3TB/3AGAHpz/AIaL5BK04vOGN7FaY1joMARlo2kRmYazAR59VPGlITgiYN+EWXyAcBaSbJjg6D17SVI6q30PCpzkUQxtTNtKs1VUm3Z3Y4PU/iA5kJtib0Povy7/Lktdqa/sEgwzZiwpdrus+8A219Hi1xFeUCxWW4qk=
