sudo: required
language: node_js
node_js:
- 4.1.1
deploy:
- provider: heroku
  app: bootstrap-api
  api_key:
    secure: b29g1AzaKZzqlVYBcgdRQTuH7Y6bK30a6HAf7Q/zyXDa19qnQFADLVoXvySU184zWAb2Ves146u50Bq2OPamEBBCB0yR55NcaZZ//Db9AI+4mDORZn/UcaQTWPWYEfE+ZExMw19l9j0tJ8mqZOxWbs95WM3PMHmd+OzgU/4xSLpc/mOESqviFaxiVKqO4p1eD0UV/evhwejlrJOKvD/rdvKTpk9ctjD2qZ9jk99Q/dFrBdxhdo1vPE1WhEd4snoFVv6zK/pw7k72Qa4jMBk4jcvV0yifsqek3X98KJEBrMKSvyMAqsl6zkFga59ryUfEVumRsf5CY35suDaQZxXv0dKZAep5mo4zjP7acmsFCut75ZLHgj1tE7mAXUMea6jciSsclVa1bK68alDbKPNBFZCgMQkKgU12HarewDZRGuJfomhfcA51Wi35mLBgbX8nKXHSf1w3mzFm6sh9iELtm1YtwphqJVQod7YcWjNnjUJwBMFh6BtQwlfmbQGeEU1wnTpdDLsna6n2KuDE85tPI1qzqMSDWUhvt5tMBUcOVNYE0EEhhx9tYsU5j2pAtmIJna1T2V0jjgr8yV1sUQ6OYpX72xvDPg+qkqbiyB+i7Rc+Z/l142ZxTSeCC1IwPlne79vfIs+zoowyfDzUmRQp0SVygKBZKSRoU07PkAmVl4c=
